# /microservices-docker/client-management-service/compose-service.yml
services:
  client-service:
    build: .
    container_name: client-management-service
    environment:
      - PORT=3007
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@client_db:27017/client_db?authSource=admin
      - AUDIT_SERVICE_URL=http://auditlog-service:3005/api/v1/audit/logs
    depends_on:
      - client_db
    networks:
      - cluster_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M