# /microservices-docker/reservation-service/compose-service.yml
services:
  reservation-service:
    build: .
    container_name: reservation-service
    environment:
      - PORT=3009
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@reservation_db:27017/reservation_db?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - AUDIT_SERVICE_URL=http://auditlog-service:3005/api/v1/audit/logs
      - NOTIF_SERVICE_URL=http://notification-service:3008/api/v1/notifications/send-email
    depends_on:
      - reservation_db
    networks:
      - cluster_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M